# Generated by Django 6.1 on 2026-08-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('matricula', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LotacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Data de início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.funcao', verbose_name='Função')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.funcionario', verbose_name='Funcionário')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.setor', verbose_name='Setor')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Lotação do Funcionário',
                'verbose_name_plural': 'Lotações dos Funcionários',
                'ordering': ['-inicio'],
            },
        ),
    ]
