# Generated by Django 6.1 on 2026-08-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario_lotacaofuncionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiderancaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liderancas', to='cadastros.funcionario', verbose_name='Líder')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liderancas', to='cadastros.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Liderança de Setor',
                'verbose_name_plural': 'Lideranças de Setores',
                'ordering': ['setor__nome', 'funcionario__nome'],
            },
        ),
    ]
