# Generated by Django 6.1 on 2026-08-20 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0005_funcionario_lotacaofuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ENVIADA_RH', 'Enviada ao RH'), ('EM_CONFERENCIA', 'Em conferência'), ('APROVADA', 'Aprovada'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_horas_extras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias_horas_extras', to='cadastros.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Competência de Hora Extra',
                'verbose_name_plural': 'Competências de Horas Extras',
                'ordering': ['-ano', '-mes', 'setor__nome'],
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('intervalo_minutos', models.PositiveIntegerField(default=0, verbose_name='Intervalo em minutos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='horas_extras.competenciahoraextra', verbose_name='Competência')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extras', to='cadastros.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Hora Extra',
                'verbose_name_plural': 'Horas Extras',
                'ordering': ['-data', 'funcionario__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='competenciahoraextra',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'setor'), name='competencia_he_unica_por_setor'),
        ),
    ]
