# Generated by Django 6.1 on 2026-08-20 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario_lotacaofuncionario'),
        ('horas_extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='competenciahoraextra',
            name='competencia_he_unica_por_setor',
            constraint=models.UniqueConstraint(fields=('ano', 'mes', 'setor'), name='competencia_he_unica_por_setor', violation_error_message='Já existe uma competência de horas extras para este setor neste mês e ano.'),
        ),
    ]
