# Generated by Django 6.1 on 2026-08-21 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0002_alter_competenciahoraextra_competencia_he_unica_por_setor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciahoraextra',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_he_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='conferencia_iniciada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conferência iniciada em'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='conferencia_iniciada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_he_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Conferência iniciada por'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='enviada_rh_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviada ao RH em'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='enviada_rh_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_he_enviadas_rh', to=settings.AUTH_USER_MODEL, verbose_name='Enviada ao RH por'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='fechada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechada em'),
        ),
        migrations.AddField(
            model_name='competenciahoraextra',
            name='fechada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competencias_he_fechadas', to=settings.AUTH_USER_MODEL, verbose_name='Fechada por'),
        ),
    ]
