# Generated by Django 6.1 on 2026-08-21 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0003_competenciahoraextra_aprovada_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciahoraextra',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ENVIADA_RH', 'Enviada ao RH'), ('EM_CONFERENCIA', 'Em conferência'), ('DEVOLVIDA', 'Devolvida para correção'), ('APROVADA', 'Aprovada'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='MovimentacaoCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADA', 'Competência criada'), ('ENVIADA_RH', 'Enviada ao RH'), ('CONFERENCIA', 'Conferência iniciada'), ('APROVADA', 'Competência aprovada'), ('DEVOLVIDA', 'Devolvida para correção'), ('REENVIADA', 'Reenviada ao RH'), ('FECHADA', 'Competência fechada')], max_length=30, verbose_name='Ação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Realizado em')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='horas_extras.competenciahoraextra', verbose_name='Competência')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_competencias_he', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação da Competência',
                'verbose_name_plural': 'Movimentações das Competências',
                'ordering': ['-criado_em'],
            },
        ),
    ]
