# Generated by Django 6.1 on 2026-08-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0004_alter_competenciahoraextra_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenciahoraextra',
            options={'ordering': ['-ano', '-mes', 'setor__nome'], 'permissions': [('visualizar_horas_extras', 'Pode visualizar horas extras'), ('lancar_horas_extras', 'Pode lançar horas extras'), ('enviar_horas_extras_rh', 'Pode enviar horas extras ao RH'), ('conferir_horas_extras', 'Pode conferir horas extras'), ('aprovar_horas_extras', 'Pode aprovar horas extras'), ('devolver_horas_extras', 'Pode devolver horas extras para correção'), ('fechar_horas_extras', 'Pode fechar horas extras')], 'verbose_name': 'Competência de Hora Extra', 'verbose_name_plural': 'Competências de Horas Extras'},
        ),
    ]
