# Generated by Django 6.1 on 2026-08-22 13:27

from django.db import migrations

def criar_perfis_horas_extras(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    grupo_lider, _ = Group.objects.get_or_create(
        name="Líder"
    )

    grupo_rh, _ = Group.objects.get_or_create(
        name="RH"
    )

    permissoes_lider = Permission.objects.filter(
        content_type__app_label="horas_extras",
        codename__in=[
            "visualizar_horas_extras",
            "lancar_horas_extras",
            "enviar_horas_extras_rh",
        ],
    )

    permissoes_rh = Permission.objects.filter(
        content_type__app_label="horas_extras",
        codename__in=[
            "visualizar_horas_extras",
            "conferir_horas_extras",
            "aprovar_horas_extras",
            "devolver_horas_extras",
            "fechar_horas_extras",
        ],
    )

    grupo_lider.permissions.add(*permissoes_lider)
    grupo_rh.permissions.add(*permissoes_rh)


def remover_perfis_horas_extras(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    Group.objects.filter(
        name__in=[
            "Líder",
            "RH",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0005_alter_competenciahoraextra_options'),
    ]

    operations = [
        migrations.RunPython(
            criar_perfis_horas_extras,
            remover_perfis_horas_extras,
        ),
    ]
