# Generated by Django 6.1 on 2026-09-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0006_criar_perfis_horas_extras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendenciaHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observação do RH')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('resolvida', models.BooleanField(default=False, verbose_name='Resolvida')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_horas_extras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('hora_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='horas_extras.horaextra', verbose_name='Hora extra')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_horas_extras_resolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Resolvida por')),
            ],
            options={
                'verbose_name': 'Pendência de Hora Extra',
                'verbose_name_plural': 'Pendências de Horas Extras',
                'ordering': ['-criada_em'],
            },
        ),
    ]
